name: tests

on:
  push:
    branches: ["main", "next"]
  pull_request:
  workflow_dispatch:

jobs:
  checkout-and-test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: install
        run: npm ci
      - name: playwright install
        run: npx playwright install
      - name: Run swup validate tests
        run: npm run test
